### ISSUE TITLE
I cannot open this with Android Studio

### ISSUE THREAD

**Issue by adetheprince** [batuhand/dictionary-app#1]
Help needed please, can you change this project language?

**Comment by batuhand** [comment]
I couldn't see any issue about opening in android studio. You can change the project language level or sdk versions in build.gradle or pubspec.yaml files.

**Comment by adetheprince** [comment]
11:56	Android Gradle build script found: android

11:56	Frameworks Detected
			Android framework is detected.
			Configure

Its not gradle project so android studio didnt work for me.
Any help how to configure it to android studio? 
Also can you make this project to suit my needs eg my language to English for IOS and Android, I dont mind to pay and even modified my self. Let me know how much.
Thanks.

**Comment by batuhand** [comment]
App is written in flutter, so you have to install flutter plugin in android studio and framework problem will be solved.
